# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fetcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fetcher
  pod 'PKHUD'
  pod 'Alamofire', '4.9'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher'
  
  target 'FetcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
